- collector/collector.go
- engine/env.go
- engine/exec.go
- engine/flags.go
- engine/lang.go
- engine/program.go
- engine/report.go
- lang/aladino/env.go
- lang/aladino/eval.go
- lang/aladino/exec.go
- lang/aladino/interpreter.go
- lang/aladino/report.go
- plugins/aladino/actions.go
- plugins/aladino/builtins.go
- plugins/aladino/functions.go
- runner.go
This pull request decouples the reporting capabilities from the execution of aladino program that is synthesised by the evaluator. 
It also makes a series of isolated refactorings that can be identified by the commit messages.
> Decouple report from program execution

- engine/lang.go
- engine/loader.go
This pull request adds a new YAML property to define failure mode called "skip-fail-on-error" which by default is `false`.
Closes #28.
> Add YAML property to define failure mode

- plugins/aladino/actions.go
- plugins/aladino/actions_test.go
- plugins/aladino/builtins.go
This pull request introduces a new action called $assignTeamReviewer() that requests the review of a given set of team slugs.
It was also added unit tests for this action.
Documentation: https://github.com/reviewpad/docs/pull/3
Closes #26.
> Request the review of a set of teams

- lang/aladino/report.go
- plugins/aladino/actions.go
- utils/github.go
This pull request includes the following changes:
- Paginate list comments request made in `FindReportComment` function present in `lang/aladino/report.go`
- Added the `opts` argument in `GetPullRequestComments` function present in `utils/github.go`. This was added because when we want to make a request to list the comments of pull request we may want to add a set of options for this listing and this options may vary according to the context of the `GetPullRequestComments` function call. For example, the call made in `FindReportComment` in `lang/aladino/report.go` and the call made in `plugins/aladino/actions.go` differ.
Closes #9
> Paginate list comments request in aladino report

- .github/workflows/reviewpad.yml
- reviewpad.yml
In this pull request the version of reviewpad action is updated to v3.x. This version is still a WIP.
With this version comes the ability to listen to GitHub events and react to them.
The changes include:
- `.github/workflows/reviewpad.yml`
- Rename action name to `Reviewpad` instead of `Reviewpad Action` 
- Run lint
- Use action v3.x
- `reviewpad.yml`
- Add CI=green condition before merge.
> Update reviewpad action to v3.x

- plugins/aladino/actions/merge.go
- plugins/aladino/actions/merge_test.go
This pull request introduces unit tests for the merge action builtin.
Besides this, it was removed from the merge action builtin code the checks that are made to the provided args len and type since this is done before the execution of the builtin.
> Add unit tests for `$merge` action builtin

- go.mod
- mocks/aladino/mocks.go
- plugins/aladino/actions/removeLabel.go
- plugins/aladino/actions/removeLabel_test.go
This pull requests introduces the following:
- removal of args length and type check in removeLabel action builtin since these checks are already made before the action execution;
- add labels to the pull request mocks;
- add unit tests for the `removeLabel` action builtin.
> Add unit tests for `$removeLabel` action builtin

- plugins/aladino/functions/commits.go
- plugins/aladino/functions/commits_test.go
- utils/github.go
This pull request adds unit tests for the `$commits` function builtin and it paginates the `ListCommits` github request.
Closes #46
Ran the command `task test`.
> Add unit tests for `$commits` function builtin

- plugins/aladino/functions/createdAt_test.go
This pull request adds unit tests for the `$createdAt` function builtin.
It wasn't possible to develop a unit test for the case of when the `time.Parse` throws an error since the `createdAt` parameter returned by GitHub is assumed to be valid at all times and so the parse will be successful at all times supposedly.
*None*
> Add unit tests for `$createdAt` function builtin

- mocks/aladino/mocks.go
- plugins/aladino/functions/isDraft.go
- plugins/aladino/functions/isDraft_test.go
This pull request introduces `$isDraft` unit tests.
*None*
> Add `$isDraft` function unit tests

- lang/aladino/parse.go
- lang/aladino/parse_test.go
Fix adds support multiline strings in yaml config
Closes [issue #89](https://github.com/reviewpad/reviewpad/issues/89)
Use rewiewpad as CLI with this config part
```yaml
workflows:
- name: label-pull-request-with-size
description: Label pull request with size
if:
- rule: isSmall
extra-actions:
- >
$addLabel("small
multiline")
- rule: isMedium
extra-actions:
- >
$addLabel("medium
multiline")
- rule: isLarge
extra-actions:
- >
$addLabel("large
multiline")
```
> fix: yaml multiline, issue #89

- cmd/cli/main.go
- fix incorrect error messages in cli
As I was trying to do a dry run using the cli I was faced with a confusing error message saying `Missing argument reviewpad.` even though the `-reviewpad` flag was provided, turns out I was missing the `-pull-request` flag and the cli was printing out an incorrect error message.
I did a manual test by running the cli with missing arguments and checked if the intended error message was printed
> fix: :bug: fix incorrect error messages in cli

- plugins/aladino/actions/assignReviewer.go
- plugins/aladino/actions/assignReviewer_test.go
Fix don't re-request review if pr already approved
Closes [issue #89](https://github.com/reviewpad/reviewpad/issues/118)
> fix: not request review already approved pr

- lang/aladino/type.go
- lang/aladino/type_internal_test.go
This pull request introduces unit tests for `lang/aladino` type.
It was also removed the `TimeType` struct because it wasn't being used.
~
*None*
> test: add unit tests for lang/aladino type

- lang/aladino/type_internal_test.go
This pull request renames the `lang/aladino` type unit tests for the agreed format: `Test[MethodName](_When[StateUnderTest])()`.
*None*
Ran `task test`.
> refactor: rename lang/aladino type unit tests

- lang/aladino/env.go
- lang/aladino/env_test.go
- lang/aladino/expr.go
- lang/aladino/interpreter_internal_test.go
- lang/aladino/mocks.go
- lang/aladino/typeinfer.go
- lang/aladino/typeinfer_internal_test.go
This pull request introduces unit tests for `lang/aladino` typeinfer.
It also removes the period from error messages because error strings should not end with punctuation since they are usually printed following other context (https://github.com/golang/go/wiki/CodeReviewComments#error-strings).
*None*
Ran `task test` cmd
> test: add unit tests for lang/aladino typeinfer

- plugins/aladino/builtins.go
- plugins/aladino/functions/reviewerStatus.go
- plugins/aladino/functions/reviewerStatus_test.go
- utils/github.go
- utils/github_test.go
This pull request introduces a built-in utility function `$reviewerStatus`.
Closes #160
Ran `task test` command and also checked  coverage using `task coverage`
> Add  built-in utility function `$reviewerStatus`

- plugins/aladino/functions/reviewerStatus.go
- utils/github.go
- utils/github_test.go
This pull request introduces the following changes:
- Moves functionality from the host-event-handler to utils/github.com
- Minor improvement to `GetPullRequestReviews`
None.
> [ship]: add GetPullRequests to utils/github

- plugins/aladino/actions/assignReviewer.go
- plugins/aladino/actions/assignReviewer_test.go
This pull request fixes a previous implementation of #118 in which only reviewers are excluded from the review assignment if they have previously approved the pull request
Fixes #118 
> fix: only exclude reviewers that have approved the pull request

- cmd/cli/main.go
Right now when the event payload is not provided when running reviewpad cli, the cli fails.
This is because the cli tries to parse an empty event.
The proposed solution is to assume the event as empty, warn the user, and procced without the event.
Close #178
The cli was ran without a playload event.
> fix: use empty event when not provided on cli

- reviewpad.yml
This pull request introduces the workflow `attention-set` for reviewpad configuration.
_none_
Ran `reviewpad-cli` command.
> feat: add attention set workflow for reviewpad configuration

- scripts/resources/exclude-from-code-coverage.txt
This pull request introduces the removal of mock files in the code coverage by adding the file path pattern that matches `/mocks.go` to `exclude-from-code-coverage.txt` which is a file containing the file patterns regex which will be consumed by the `exclude-from-code-coverage.sh` script that removes from the code coverage the files that match the file patterns mentioned before.
Closes #191
Ran the `go tool cover -func coverage.out` that lists the files part of the code coverage with the covered percentage and it also presents at the end the total coverage percentage - with this it was verified that the parser and mock files didn't belong to this listing and the total coverage increased.
> feat: remove mocks files from code coverage

- engine/exec.go
- engine/exec_test.go
- engine/loader_test.go
- engine/mocks.go
- engine/testdata/exec/reviewpad_with_activated_workflow_with_extra_actions.yml
- engine/testdata/exec/reviewpad_with_invalid_group.yml
- engine/testdata/exec/reviewpad_with_invalid_workflow.yml
- engine/testdata/exec/reviewpad_with_multiple_activated_workflows.yml
- engine/testdata/exec/reviewpad_with_no_activated_workflows.yml
- engine/testdata/exec/reviewpad_with_one_activated_workflow.yml
- engine/testdata/exec/reviewpad_with_skipped_workflow.yml
- engine/testdata/exec/reviewpad_with_unnamed_label.yml
- engine/testdata/exec/reviewpad_with_valid_group.yml
- engine/testdata/exec/reviewpad_with_valid_label.yml
- engine/testutils/parse.go
- utils/file/file.go
- utils/load.go
This pull request introduces the unit tests for engine exec and some extra mocks related to the pull request data.
During the development of the unit tests, it was encountered an error in the `CollectError` function where it wasn't being taken into account the `*github.ErrorResponse` error type and this would cause an nil pointer dereference because the `Error()` method would be applied to this object which doesn't support such thing and so we need to manually get the error string in this case.
Closes #176
> test: add unit tests for engine exec

- plugins/aladino/builtins.go
- plugins/aladino/functions/sprintf.go
- plugins/aladino/functions/sprintf_test.go
Feat adds formated string buit-in
Closes [issue #195](https://github.com/reviewpad/reviewpad/issues/195)
> feat: sprintf returns formated string

- codehost/github/projects.go
- codehost/github/projects_test.go
- plugins/aladino/actions/addToProject_test.go
Fixed issue when we get project with similar name
Closes [issue #222](https://github.com/reviewpad/reviewpad/issues/222)
run tests
[x] Ask: this pull request requires a code review before merge
> fix: addToProject fetches the wrong project

- codehost/github/issues.go
- handler/processors.go
- handler/processors_test.go
This pull request introduces the following changes:
- Paginate the request for GitHub issues.
- Extend the cron event to retrieve all issues (including pull requests).
Closes #298.
> feat: extend cron event for issues and pull requests

- .github/workflows/build.yml
- .github/workflows/pull_request_build.yml
- ci/baseimage/dockerfile
This pull request introduces the use of reviewpad ci image for the build.
A reviewpad image is required due to the use of libgit2.
Closes #312
Created a fork under ferreiratiago/reviewpad and tested.
> chore: update ci build to use reviewpad ci container image

- engine/loader.go
- engine/transform.go
- engine/transform_internal_test.go
- plugins/aladino/builtins.go
- plugins/aladino/functions/issueCountBy.go
- plugins/aladino/functions/issueCountBy_test.go
- plugins/aladino/functions/pullRequestCountBy.go
- plugins/aladino/functions/pullRequestCountBy_test.go
This pull request introduces the following changes:
- Adds $issueCountBy built-in 
- Adds $pullRequestCountBy built-in
- Extends the transformation of Aladino actions to Aladino expressions to add optional arguments the xCountBy built-ins
- Adds unit tests to the transformation
Corresponding pull request: https://github.com/reviewpad/docs/pull/27
Closes #308
> feat: issue and pull request count by built-ins

- codehost/github/pull_requests_test.go
This pull request introduces the improvement of PaginatedRequest and ParseLink related tests in order to adopt the TDT format; another improvement made was the adoption of `mock.WithRequestMatchPages` in order to mock paginated requests.
Besides this, it was removed the unit tests for getters since there is no logic to be tested there.
_Edit:_
It was disregarded the usage of `mock.WithRequestMatchPages` since this wouldn't help us cover the scenario of when a non first page request failed because we can't force an error for this request using the mentioned method.
Said that, we implement the pagination mock explicitly using `httpmock` for only 2 pages request.
*None*
> test: improve PaginatedRequest and ParseLink tests

- engine/normalize.go
- engine/normalize_test.go
normalize function takes as its argument pointer to the *ReviewpadFile, and normalizes its property values. 
"normalize" means validate, modify, check, and assign a default value if empty by specified rules. If no customNormalizeRules passed as a second argument, default normalize rules are used. 
#162 
Unit tests in engine/normalize_test.go for default and custom normalize rules
> feat: normalize ReviewpadFile functionality

- .editorconfig
The existing `editorconfig` configuration file had a couple of issues. One of them I detailed in #342, but the second I only really noticed after I was already tweaking the configuration. The two issues were:
- Editorconfig was set up for using 4 Spaces for indentation, even in Go files, which use tabs
- Because of the way the file was structured, many of the rules weren't matching for all files (they were only matching for `YAML` files)
This changeset fixes both issues. It adds a lean configuration specifically for Go files (it only really imposes the use of tabs), and moves the rules below to the top level (any file) configuration. These rules were being ignored for non-YAML files since 9f1b7fbe982c63bef7f149338cc5423fd7aea226, because of how the file was re-structured in that …
> fix: Editorconfig config file tweaks

- engine/exec_test.go
- engine/labels.go
- engine/labels_internal_test.go
When describing label colors while editing the Reviewpad configuration file, it is often useful to visualize the colors in place without having to copy the hex values somewhere else. The current [Reviewpad specification](https://docs.reviewpad.com/guides/syntax#label) for labels requires hex values defined in the configuration to _not_ include the number sign. That means mechanisms that detect hex color values will not match. Like so:
Very uncool:
Isn't this a lot better:
This changeset makes the number sign optional, by doing 2 main things:
- The regex that matches and validates colors now allows for an optional `#` (e.g: `#abcdef` is now valid)
- Before we [push the label to Github](https://docs.github.com/en/rest/issues/labels#create-a-label), we trim the `#` if it exists [^1]
Closes …
> feat: Allow number sign in label color hex values

- engine/transform.go
- engine/transform_internal_test.go
- lang/aladino/parser.go
- plugins/aladino/functions/size.go
- plugins/aladino/functions/size_test.go
Adds patterns to Size built-in
Closes [issue #89](https://github.com/reviewpad/reviewpad/issues/268)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
!!! now all Size built-in expects empty arrays as pattern, it wouldn't work without params as earlier
run tests and try to run reviewpad as a CLI with new config
> feat: add patterns to size built-in

- lang/aladino/expr.go
- lang/aladino/expr_internal_test.go
- lang/aladino/lex.go
- lang/aladino/parse_test.go
This pull request introduces a fix to the bug string literal regex breaking for strings which contain other strings.
This bug was occuring because it was being done the escaping of `"` inside the string.
This fix was based on https://gist.github.com/cellularmitosis/6fd5fc2a65225364f72d3574abd9d5d5.
We only add the escape for the `reviewpad.yml`. Internally, we remove this escape (upon building strings) because we only use the escape for parsing effects and furthermore this escape is not needed anymore.
Closes #370 
Ran `task check -f` cmd and performed tests against a testing repo.
> fix: string literal regex breaks for strings which contain other strings

- codehost/github/pull_requests.go
- codehost/github/pull_requests_test.go
This pull request handles the case of `pushedDate` being `nil` when executing [`GetPullRequestLastPushDate`](https://github.com/reviewpad/reviewpad/blob/main/codehost/github/pull_requests.go#L360) in the case scenario of the last pull request event being a commit.
The handling of this consists in considering the `CommittedDate` of the commit.
Closes #379 
> fix: no alternative for when pushedDate is nil

- stale.yml
This pull request improves the reviewpad yml configuration for stale issues/pull requests by not performing the stale labelling if the issues are already labeled as "good first issues".
Closes #383 
Ran `./reviewpad-cli check` cmd in order to check the linting of the file and ran this configuration against a testing repo.
> feat: ignore stale labeling for good first issues

- codehost/github/pull_requests.go
- codehost/github/target/pull_request_target.go
- plugins/aladino/actions/review.go
- plugins/aladino/actions/review_test.go
- plugins/aladino/builtins.go
Adds new built-in $review
Closes [issue #384](https://github.com/reviewpad/reviewpad/issues/384)
Use rewiewpad as CLI with test config
> feat: add review built-in

- cli/cmd/run.go
- collector/collector.go
- engine/mocks.go
- lang/aladino/mocks.go
This pull request makes the following changes:
- Adds a property `runnerEnv` to the `collector` struct to represent the env where Reviewpad is running;
- Updates the callers of the collector to use the property.
Closes #417
None.
> feat: add runner env property to mixpanel collector

- codehost/diff.go
This PR fixes the incorrect conversion between integer types code scanning alert by parsing numbers that are cast to int32 as 32bit
Closes #439 
This was tested by building a CodeQL database locally and running the `IncorrectIntegerConversionQuery.ql` query and checking the result
> fix: incorrect conversion between integer types code scanning alert

- engine/transform.go
- engine/transform_internal_test.go
- plugins/aladino/functions/issueCountBy.go
- plugins/aladino/functions/pullRequestCountBy.go
This PR adds a default state(all) to the `$pullRequestCountBy` and `$issueCountBy` built-ins
Closes #434 
Unit and manual tests
> fix: add default state for pullRequestCountBy and issueCountBy built-ins in transform

- codehost/github/target/pull_request_target.go
- plugins/aladino/actions/assignReviewer.go
- plugins/aladino/actions/assignReviewer_test.go
This PR updates the `$assignReviewer` built-in action so that it checks the last pushed date before re-requesting a review
Closes #415 
Unit tests and manual tests
> fix: don't re-request review unless a new commit has been pushed

- plugins/aladino/functions/sprintf.go
- plugins/aladino/functions/sprintf_test.go
This PR improves the `$sprintf` built-in by ignoring extra args
Closes #450 
Unit & Manual tests.
> fix: ignore extra args to sprintf built-in function

- codehost/github/target/issue_target.go
- codehost/github/target/pull_request_target.go
- codehost/target.go
- lang/aladino/mocks.go
- plugins/aladino/builtins.go
- plugins/aladino/functions/state.go
- plugins/aladino/functions/state_test.go
This pull request introduces a new built-in $state() that retrieves the state of a pull request.
According to the GitHub API, this can be either "open" or "closed".
Closes #444
Locally tested.
> feat: state built-in for issues and pull requests

- codehost/github/issues.go
- codehost/github/issues_test.go
- codehost/github/repo.go
- codehost/github/target/common_target.go
- codehost/github/target/issue_target.go
- codehost/github/target/pull_request_target.go
- codehost/target.go
- engine/exec.go
- plugins/aladino/builtins.go
- plugins/aladino/functions/isLinkedToProject.go
- plugins/aladino/functions/isLinkedToProject_test.go
This pull request introduces the built-in $isLinkedToProject that receives a project name and returns true/false depending on whether the issue or pull request is already associated with the project.
Closes #483 
Unit tests for GetLinkedProjects GraphQL.
This built-in was functionally tested with success in the GitHub action with branch: https://github.com/reviewpad/action/tree/dev/add-to-project-usecase
> feat: add isLinkedToProject built-in

- engine/exec.go
- engine/exec_test.go
- utils/pr.go
- utils/pr_test.go
Currently, when command errors such as syntax or invalid flag errors happen, we edit the user's comment to provide feedback, this PR modifies reviewpad so instead of editing the comment, feedback is provided as a new comment.
Closes #472 
Closes #473 
Unit & Manual Tests.
> feat: provide command error feedback as comment

- engine/lang.go
- engine/lang_internal_test.go
- engine/loader_test.go
- engine/testdata/loader/process/reviewpad_with_extends_after_processing.yml
- engine/testdata/loader/reviewpad_with_no_extends_a.yml
- engine/testdata/loader/reviewpad_with_no_extends_b.yml
This pull request introduces the following changes:
- Unit tests to compare that the loader does not 'default' fields in the Reviewpad file;
- Use a pointer to represent the ignore errors field;
- Extend the `extends` functionality for the rest of the ReviewpadFile fields.
Closes #523
Bug fix (non-breaking change which fixes an issue) 
Unit tests.
> fix: extends for all properties of reviewpad file

- plugins/aladino/actions/merge.go
- plugins/aladino/actions/merge_test.go
This pull request refines the $merge() built-in to only be enabled on open and non-draft pull requests.
Closes #525
Unit tests.
Functional validation with canary version of GitHub Action.
> feat: merge built-in is only enabled on open and non-draft prs

- engine/linter.go
This pull request lowers the severity of unused rules in the linter from error to log. 
Closes #531.
Functional testing using GitHub action.
> fix: log unused rules instead returning error

- engine/exec.go
- engine/exec_test.go
- engine/labels.go
This pull request updates the color property in the labels.
Closes #530
Bug fix (non-breaking change which fixes an issue) 
Functional tests:
> fix: update label color property

- engine/env.go
- engine/inline_rules_normalizer.go
- engine/lang.go
- engine/loader.go
- engine/loader_internal_test.go
- engine/loader_test.go
- engine/testdata/loader/process/reviewpad_with_extends_after_processing.yml
- engine/testdata/loader/reviewpad_with_no_extends_a.yml
- lang/aladino/interpreter.go
- lang/aladino/interpreter_internal_test.go
- runner.go
This pull request introduces the `metrics-on-merge` flag that controls if the metrics report is presented when a pull request is merged.
Closes #532
Unit tests.
> feat: metrics-on-merge flag

- codehost/github/target/pull_request_target.go
- codehost/github/workflows.go
- plugins/aladino/actions/triggerWorkflow.go
- plugins/aladino/builtins.go
- plugins/aladino/functions/eventType.go
- plugins/aladino/functions/eventType_test.go
This pull request introduces two new built-ins:
- $triggerWorkflow(file) that triggers a workflow from the GitHub action file name
- $eventType() that returns the type of pull request event
Unit tests and functional tests.
> feat: trigger workflow and event type built-ins

- plugins/aladino/functions/filesPath_test.go
Fixes intermittently failing test cases for `$filesPath` built-in function, the issue was since the patch is a map and iterating over it is non-deterministic.
Closes #575 
Running the tests with a count of 10 and make sure it didn't fail.
> fix: randomly failing filesPath tests

- plugins/aladino/builtins.go
- plugins/aladino/functions/toBool.go
- plugins/aladino/functions/toBool_test.go
Adds a new `$toBool` built-in function. this built-in is basically a wrapper of `strconv.ParseBool` and  It accepts 1, t, T, TRUE, true, True, 0, f, F, FALSE, false, False. Any other value returns an error
- `$toBool("true")`
- `$toBool("false")`
- `$toBool($selectFromContext("$.locked"))`
Closes #586 
Unit tests and manual tests
> feat: toBool built-in function

- lang/aladino/type.go
- lang/aladino/type_internal_test.go
- plugins/aladino/functions/sprintf.go
- plugins/aladino/functions/sprintf_test.go
Extends the `$sprintf` built-in function to support integers and booleans.
Closes #579 
Unit tests and manual tests
> feat: extend sprintf to support other types

- engine/transform.go
- engine/transform_internal_test.go
Fixes the `$join` built-in functions default separator transformer.
The problem was the `addDefaultJoinSeparator` function, in order to support nested joins used a regular expression that caused it to add the default separator in the wrong place for certain conditions. Unfortunately, this fix has the side effect of causing the default function not to provide defaults for nested joins.
Closes #583 
Unit tests and manual tests
> fix: join separator default function

- lang/aladino/mocks.go
- plugins/aladino/actions/review.go
- plugins/aladino/actions/review_test.go
- plugins/aladino/functions/context_test.go
This pull request improves the `$review` built-in functionality by only submitting a review when the last review made by the bot was made before the last pull request push. Besides this, reviews are only performed on open pull requests.
Closes #577 
Manual tests and ran `task check` cmd.
> feat: review only if pull request has updates

- engine/commands/assignRandomReviewer.go
- engine/commands/assignRandomReviewer_test.go
- engine/commands/commands.go
This pull request introduces the `$assignRandomReviewer` command.
Syntax: 
`/reviewpad assign-random-reviewer`
Closes #419 
Manual tests and ran the `task check` cmd.
> feat: assign random reviewer command

- plugins/aladino/actions/deleteHeadBranch.go
- plugins/aladino/actions/deleteHeadBranch_test.go
Checks a pull request isn't from a fork before attempting to delete the head branch on the `$deleteHeadBranch` built-in action. Attempting to delete the head branch of the pull request without checking if it's from a fork causes the `Reference does not exist` error
Closes #620 
Unit & Manual tests
> fix: delete head branch reference does not exist issue

- codehost/github/client.go
- codehost/github/repo.go
- plugins/aladino/actions/rebase.go
Currently, we are getting the github token for the `rebase` built-in through the `INPUT_TOKEN` env variable, the problem is the `$rebase` built-in will fail if that env isn't present, this PR updates the built-in so it can get it's token from the github client.
Closes #633 
Manual tests
> refactor: rebase token from client

- engine/exec_test.go
- engine/lang.go
- engine/loader.go
- engine/loader_test.go
- runner.go
This pull request introduces the logging for overridden reviewpad properties by the extend property.
This logging says which properties were overridden and the property type.
Closes #517
Ran manual tests with `reviewpad-cli`.
> feat: add logging info for overrides

- cli/cmd/run.go
- runner.go
This is a basic refactor that removes the event payload as it is already passed in the event details.
Closes #615.
Unit tests.
> refactor: remove event from reviewpad run input

- lang/aladino/interpreter.go
- lang/aladino/interpreter_internal_test.go
- lang/aladino/report.go
- lang/aladino/report_internal_test.go
- plugins/aladino/actions/comment.go
- plugins/aladino/actions/commentOnce.go
- plugins/aladino/actions/commentOnce_test.go
- plugins/aladino/actions/comment_test.go
This pull request introduces the annotation comment `` with the purpose of ignoring Reviewpad comments.
Closes #645 
Manual tests.
> feat: add annotation to ignore comment

- plugins/aladino/functions/haveAllChecksRunCompleted.go
- plugins/aladino/functions/haveAllChecksRunCompleted_test.go
This pull request introduces the fix to the built-in `haveAllChecksRunCompleted` by ignoring the Reviewpad check by default.
Closes #655
Manuel tests
> fix: ignore reviewpad check runs by default

- engine/loader.go
- engine/loader_test.go
This pull request implements a feature to detect when a "404 Not Found" error is due to reviewpad not having access to the `reviewpad.yml` files that come from the `extends` property. The code checks the error message from the GitHub API after trying to download a file from a repository. If the error message is "Not Found" or "Repository access blocked", the error is likely due to reviewpad not being installed on a private repository. If it's not due to this reason, the error may be due to other factors.
It's worth noting that "404 Not Found" is a general HTTP error indicating that the requested resource could not be found on the server. On the other hand, "Repository access blocked" is a specific error message generated by GitHub indicating the user doesn't have sufficient permissions to …
> feat: extend config unauthorized err handling

- lang/aladino/interpreter_internal_test.go
- lang/aladino/report.go
- lang/aladino/report_internal_test.go
This pull request resolves the issue where the Reviewpad generates an empty report when the `mode` property is set to `verbose`. The solution handles the scenario where there are no actions executed by generating a report indicating this, otherwise, it presents a list of the actions executed.
Closes #654 
Manual tests (described here https://www.notion.so/reviewpad/Reviewpad-generates-an-empty-report-e5eb16579ae84e2ab10f4464241a2dc9) and ran the `task check -f` cmd.
> fix: empty reviewpad report

- codehost/github/commits.go
- integration_test/integration_test.go
- lang/aladino/interpreter.go
- lang/aladino/interpreter_internal_test.go
Currently, the `$fail` built-in fails reviewpad, this PR modifies reviewpad so that `$fail` built-in instead of failing reviewpad creates a new commit status with a `failure` state.
Closes #652 
Manual tests performed on the action and on the github app.
> feat: separate check for fail built in

- lang/aladino/interpreter.go
- lang/aladino/interpreter_internal_test.go
- lang/aladino/report.go
- lang/aladino/report_internal_test.go
- plugins/aladino/actions/comment.go
- plugins/aladino/actions/commentOnce.go
- plugins/aladino/actions/commentOnce_test.go
- plugins/aladino/actions/comment_test.go
- runner.go
This pull request removes the `ReviewpadIgnoreCommentAnnotation` and all the code associated with it.
Closes #700 
Unit tests.
> chore: remove ReviewpadIgnoreCommentAnnotation and its references

- engine/transform.go
- engine/transform_internal_test.go
- plugins/aladino/functions/haveAllChecksRunCompleted.go
- plugins/aladino/functions/haveAllChecksRunCompleted_test.go
Adds a third parameter to the `$haveAllChecksRunCompleted` built-in function that allows the user to ignore certain conclusions
Closes #705 
Unit tests
> feat: add parameter to ignore certain conclusions in have all checks run completed

- engine/loader.go
Passes the `until` part of the pipelines through the aladino expression transformer
Closes #722 
Manual tests
> fix: transform expressions for pipeline until

- runner.go
- utils/file.go
This pull request transfers the methods that load the reviewpad file contents from GitHub and check if the pull request changes the reviewpad file which lived in the GitHub Action.
**Improvements** (non-breaking change without functionality)
Manual tests in the dev app where 2 pull requests were opened to test when:
- the changes contain the reviewpad file;
- the changes do not contain the reviewpad file.
**Ask**: this pull request requires a code review before the merge
> chore: load reviewpad file from gh method

- engine/exec.go
- engine/inline_rules_normalizer.go
- engine/lang.go
- engine/lang_internal_test.go
- engine/loader.go
- engine/loader_internal_test.go
- engine/loader_test.go
- engine/normalize.go
- engine/normalize_test.go
- runner.go
Removes the `edition` property from reviewpad configuration.
Closes #746 
**Improvements** (non-breaking change without functionality)
Manually
> refactor: remove edition property from reviewpad file

- engine/transform.go
- engine/transform_internal_test.go
- lang/aladino/lex.go
- plugins/aladino/actions/assignAssignees.go
- plugins/aladino/actions/assignAssignees_test.go
- plugins/aladino/actions/assignCodeAuthorReviewers.go
This pull request updates the `$assignAssignees` built-in to include another parameter, which is optional, that defines the total number of users to be assigned.
If the introduced parameter is not set, the default value is the total number of given users (the 1st parameter) if the total does not exceed 10. To achieve this, in the [`transform`](https://github.com/reviewpad/reviewpad/blob/main/engine/transform.go) process we set a `REVIEWPAD_DEFAULT_INT_VALUE` which is `-1` to be the default of the total required users to be assigned and on the execution of the built-in once we detect this tag we know that the total required users to be assigned should be the number of given users that can be assigned.
Closes #733
Manual tests …
> feat: select amount of desired assignees in assignAssignees

- codehost/github/repo.go
The repo cloning function currently logs the URL used for cloning exposing the access token as well in the logs, this PR converts the log level into Debug so the access token won't be exposed to users.
Closes #736 
**Improvements** (non-breaking change without functionality) 
Manual test
> fix: make cloning log debug level

- handler/types.go
This PR adds the `workflow_ref` field to the ActionEvent struct.
Closes #756 
**Ship**: this pull request can be automatically merged and does not require code review
> feat: add workflow_ref to action event struct
