reviewpad/reviewpad

- engine/env.go
- go.mod
- lang/aladino/interpreter.go
- lang/aladino/report.go
- plugins/aladino/builtins.go
- plugins/aladino/functions.go
This pull requests adds a new built-in $rule that allows rules to be defined based on other rules.
> Add $rule function builtin

- collector/collector.go
- engine/labels.go
- engine/transform.go
This pull request updates the licences in the files:
- [engine/labels.go](https://github.com/reviewpad/reviewpad/blob/235df37d0b4ba1ea44db53dd2389c6dbaeb59ebc/engine/labels.go)
- [engine/transform.go](https://github.com/reviewpad/reviewpad/blob/235df37d0b4ba1ea44db53dd2389c6dbaeb59ebc/engine/transform.go)
Closes #10
> Change licence

- engine/exec.go
- engine/lang.go
- engine/linter.go
- engine/loader.go
> [ship]: Update groups and rules properties from sets to lists 

- engine/linter.go
> [ship]: Lint rule and group references

- utils/file_test.go
This pull request adds unit test for utils file.
> Add unit test for utils file

- utils/report/error_test.go
This pull request adds unit test for utils report `Error`.
> Add unit tests for utils report `Error`

- README.md
It's a simple step, but keep the first touch in reviewpad code smooth
> Create a small section in Development about goyacc

- .github/PULL_REQUEST_TEMPLATE/general.md
Add template for pull requests.
> [ship]: Add template for pull requests

- utils/array_test.go
This pull request adds unit tests for utils array.
> Add unit tests for utils array

- .editorconfig
- README.md
[EditorConfig](https://editorconfig.org/) will help us to maintain consistent coding styles.
To run and test this it is required to install the VSCode extension for [EditorConfig](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) and add the configuration ` "editor.formatOnSave": true` to VSCode (check the details on the changed README.md file in this pr).
After that you can open any file and, for instance, remove the empty line at the end of the file and save the file. VSCode will automatically add the empty line at the end of the file.
> [ship]: Add editorconfig

- README.md
This pull request fixes a regression in the formatting from https://github.com/reviewpad/reviewpad/commit/421dab80ff13b7ceb9c673c7c9791c1703a44c5c
> [ship]: Add spaces to fix format in Architecture section

- plugins/aladino/functions/description_test.go
This pull request adds unit tests for the `$description` function builtin.
*None*
> Add unit tests for `$description` function builtin

- plugins/aladino/functions/group_test.go
This pull request adds unit tests for the `$group` function builtin.
*None*
Improvements (non-breaking change without functionality
> Add unit tests for `$group` function builtin

- plugins/aladino/functions/hasCodePattern_test.go
This pull request introduces `$hasCodePattern` unit tests.
*None*
> Add `$hasCodePattern` unit tests

- plugins/aladino/functions/hasFileExtensions_test.go
This pull request introduces `$hasFileExtensions` unit tests.
*None*
> Add `$hasFileExtensions` unit tests

- plugins/aladino/functions/hasFileName_test.go
This pull request introduces `$hasFileName` unit tests.
*None*
> Add `$hasFileName` unit tests

- plugins/aladino/functions/hasFilePattern_test.go
This pull request introduces `$hasFilePattern` unit tests.
*None*
> Add `$hasFilePattern` unit tests

- plugins/aladino/functions/isElementOf_test.go
This pull request introduces `$isElementOf` unit tests.
*None*
> Add `$isElementOf` function unit tests

- mocks/aladino/mocks.go
- plugins/aladino/functions/labels_test.go
This pull request introduces `$labels` unit tests.
*None*
> Add `$labels` function unit tests

- mocks/aladino/mocks.go
- plugins/aladino/functions/milestone_test.go
This pull request introduces `$milestone` unit tests.
*None*
> Add `$milestone` function unit tests

- mocks/aladino/mocks.go
- plugins/aladino/functions/reviewers_test.go
This pull request introduces `$reviewers` unit tests.
*None*
> Add `$reviewers` function unit tests

- plugins/aladino/functions/rule_test.go
This pull request introduces `$rule` unit tests.
*None*
> Add `$rule` function unit tests

- mocks/aladino/mocks.go
- plugins/aladino/functions/size_test.go
This pull request introduces `$size` unit tests.
*None*
> Add `$size` function unit tests

- mocks/aladino/mocks.go
- plugins/aladino/functions/title_test.go
This pull request introduces `$title` unit tests.
*None*
> Add `$title` function unit tests

- plugins/aladino/functions/hasLinearHistory_test.go
This pull request introduces `$hasLinearHistory` unit tests.
*None*
> Add `$hasLinearHistory` unit tests

- plugins/aladino/functions/organization_test.go
This pull request introduces `$organization` unit tests.
*None*
> Add `$organization` function unit tests

- utils/github_test.go
This pull request introduces unit tests for github paginated request related functions.
*None*
> Add unit tests for github paginated request functions

- utils/github_test.go
This pull request introduces unit tests for github `GetPullRequestComments` function.
*None*
> Add unit tests for github `GetPullRequestFiles`

- utils/github_test.go
This pull request introduces unit tests for github `GetPullRequestReviewers` function.
*None*
> Add unit tests for github `GetPullRequestReviewers`

- utils/github_test.go
This pull request introduces unit tests for github `GetRepoCollaborators` function.
*None*
> Add unit tests for github `GetRepoCollaborators`

- utils/github_test.go
This pull request introduces unit tests for github `GetPullRequestCommits` function.
*None*
> test: github `GetPullRequestCommits` unit tests

- .gitignore
Added the folder from IntelliJ IDEA to ignore.
It will be useful for developers who use this IDE
tests are not needed
> feat: gitignore IntelliJ IDEA folder

- lang/aladino/value_test.go
This pull request introduces unit tests for `lang/aladino/value.go`.
*None*
> test: aladino value unit tests

- lang/aladino/builtins_test.go
This pull request introduces unit test for `lang/aladino/builtins.go`.
*None*
> test: unit test for `lang/aladino/builtins.go`

- plugins/aladino/functions/filter_test.go
This pull request introduces unit tests for the `filter` function builtin.
*None*
> test: `filter` function builtin unit tests

- engine/env.go
- engine/exec.go
- runner.go
- Made sure labels aren't being created for dry runs
Closes Issue #33
I created a pull request on my repo and then using the cli
1. I first did a normal run and checked If the labels were created on the pull request ✅
2. removed the created labels ✅
3. then I did a dry run and checked no labels were created on the pull request ✅
> fix: :bug: dry runs shouldn't create labels on pull requests

- lang/aladino/diff.go
- lang/aladino/env_test.go
- lang/aladino/file.go
- lang/aladino/mocks.go
This pull request introduces unit tests for `lang/aladino/env`.
*None*
> test: lang aladino env unit tests

- lang/aladino/env_test.go
- lang/aladino/eval_test.go
- lang/aladino/mocks.go
This pull request introduces the unit tests for `lang/aladino` eval.
For this, it was also made exported the builders for TypedExpr and Lambda expressions.
*None*
> test: add unit tests for lang/aladino eval

- lang/aladino/interpreter.go
- lang/aladino/interpreter_test.go
- lang/aladino/mocks.go
This pull request introduces the unit tests for lang/aladino interpreter `ProcessGroup`.
*None*
> test: add unit tests for lang/aladino interpreter `ProcessGroup`

- lang/aladino/file_internal_test.go
- lang/aladino/file_test.go
This pull request introduces unit tests for `lang/aladino` file type.
*None*
> test: add unit tests for lang/aladino file

- lang/aladino/exec_internal_test.go
- lang/aladino/exec_test.go
- lang/aladino/mocks.go
This pull request introduces unit tests for `lang/aladino` exec, more especifically, `TypeCheckExec`.
*None*
> test: add unit tests for lang/aladino exec

- lang/aladino/report_internal_test.go
This pull request introduces unit tests for `lang/aladino` report.
*None*
> test: add unit tests for lang/aladino report

- engine/program.go
- engine/program_internal_test.go
This pull request introduces unit tests for engine program.
*None*
> test: add unit tests for engine program

- engine/env_test.go
- engine/mocks.go
This pull request introduces unit tests for engine env and mocks for engine.
*None*
> test: add unit tests for engine env & mocks for engine

- cmd/cli/main.go
- engine/env.go
- lang/aladino/env.go
- lang/aladino/env_test.go
- lang/aladino/interpreter.go
- lang/aladino/interpreter_internal_test.go
- lang/aladino/mocks.go
- lang/aladino/report.go
- lang/aladino/report_internal_test.go
- runner.go
- send dry run report
reviewpad/action#10
1. Run Reviewpad in dry run mode checked the results were as expected
> feat: :sparkles: comment dry run report

- cmd/cli/main.go
This pull request introduces a new CLI argument for the safe mode execution.
> [ship]: feat: add safe mode run as CLI argument

- lang/aladino/builtins.go
- lang/aladino/exec.go
- lang/aladino/exec_internal_test.go
- plugins/aladino/actions/disableActions.go
- plugins/aladino/actions/disableActions_test.go
- plugins/aladino/builtins.go
This pull request introduces a new built-in action called '$disableActions'.
Closes #199.
> feat: $disableActions built-in

- lang/aladino/exec.go
This pull request improves the logging when an action is disabled to be consistent with the logs.
> [ship]: chore: improve action disable logging

- engine/linter.go
- engine/linter_internal_test.go
This pull request fixes a bug when matching the spec of a rule for usages of the `$rule()` built-in.
Closes #205 
> fix: check uses of rule built-in 

- README.md
Add information to the README.md on how to run the tests and how to potentially fix a problem related to "too many open files".
> docs(README): add test information

- plugins/aladino/builtins.go
- plugins/aladino/functions/isWaitingForReview.go
- plugins/aladino/functions/isWaitingForReview_test.go
Add new builtin `isWaitingForReview`.
Documentation https://github.com/reviewpad/docs/pull/16
_none_
Ran `task check -f`.
> feat: add builtin isWaitingForReview

- .github/workflows/reviewpad.yml
- reviewpad.yml
This pull request improves attention set workflow on reviewpad configuration.
Also updates the list of events to which the reviewpad actions is triggered.
_none_
Run `reviewpad-cli`.
> feat: improve attention set on reviewpad configuration

- plugins/aladino/actions/addLabel.go
- plugins/aladino/actions/removeLabel.go
Closes #211 
- [ x] I have ran `task check -f` and have no issues
[x] Ask: this pull request requires a code review before merge
> fix: change log message format for addLabel

- lang/aladino/mocks.go
- plugins/aladino/actions/addToProject.go
- plugins/aladino/actions/addToProject_test.go
- plugins/aladino/builtins.go
- utils/github_projects.go
- utils/github_projects_test.go
- utils/test.go
- added `$addToProject` action
Closes #184 
> $addToProject built in action

- engine/exec.go
- engine/program.go
- engine/program_internal_test.go
- lang/aladino/interpreter.go
- lang/aladino/interpreter_internal_test.go
- lang/aladino/report.go
- lang/aladino/report_internal_test.go
For consistency throughout the code, this pull request adds builders to engine.Program and hides the struct elements.
It was also made the changes required to adapt to this new change, mainly in related unit tests.
Closes #157 
> refactor: add builders to engine.Program

- README.md
Fix flags description after moving to cobra lib
Changed only Readme
[x] Ship: this pull request can be automatically merged and does not require code review
> fix: updated cli run command and flags in readme

- engine/env_test.go
- engine/exec.go
- engine/program.go
- engine/program_internal_test.go
- lang/aladino/env.go
- lang/aladino/env_test.go
- lang/aladino/interpreter_internal_test.go
- lang/aladino/report.go
- lang/aladino/report_internal_test.go
This pull request simplifies the report generated in accordance to #229.
Closes #229
> feat: simplify report

- engine/exec.go
- engine/lang.go
- engine/loader.go
- engine/loader_internal_test.go
This pull request introduces the concept of pipeline as an extension of our current specification.
Closes #231.
This feature was manually tested with first basic experiments using the CLI.
> experimental: add pipelines

- Taskfile.yml
New taskfile task to check branches coverage difference
Closes [issue #232](https://github.com/reviewpad/reviewpad/issues/232)
Run task coverage-diff
[x] Ask: this pull request requires a code review before merge
> feat: coverage difference

- codehost/github/repositories.go
This pull request adds a function `DownloadContents` to the codehost.github API.
> feat: add download contents to codehost

- plugins/aladino/builtins.go
- plugins/aladino/functions/changed.go
- plugins/aladino/functions/changed_test.go
This pull request introduces the $changed built-in function that was previously part of the premium offering.
Black-box testing on the built-in. As a future improvement we should add unit tests to the auxiliary functions.
> feat: add changed built-in

- plugins/aladino/actions/errorMsg.go
- plugins/aladino/actions/errorMsg_test.go
- plugins/aladino/builtins.go
This pull request adds the `$error` action built-in (which was private before) and its corresponding unit tests.
*None*
> feat: add $error action built-in

- lang/aladino/env.go
- plugins/aladino/actions/commitLint_test.go
- plugins/aladino/actions/warn.go
- plugins/aladino/actions/warn_test.go
- plugins/aladino/builtins.go
This pull request adds the `$warn` action built-in (which was private before) and its corresponding unit tests.
*None*
> feat: add $warn built-in

- lang/aladino/env.go
- plugins/aladino/actions/commitLint_test.go
- plugins/aladino/actions/info.go
- plugins/aladino/actions/info_test.go
- plugins/aladino/builtins.go
This pull request adds the `$info` action built-in (which was private before) and its corresponding unit tests.
*None*
> feat: add $info action built-in

- lang/aladino/env.go
- lang/aladino/interpreter.go
- lang/aladino/report.go
- lang/aladino/report_internal_test.go
- plugins/aladino/actions/commitLint_test.go
This pull request updates the report generation to take into account the built-ins comments. 
Closes #264
> Update report generation for info, warn and error builtins

- go.mod
- go.sum
- plugins/aladino/builtins.go
- plugins/aladino/services/semantic.go
- runner.go
This pull request introduces a private field to the PluginConfig struct to control when the gRPC connections should be closed.
Closes #266.
Bug fix (non-breaking change which fixes an issue) 
Manual testing.
> fix: semantic client connection

- engine/mocks.go
- lang/aladino/mocks.go
This pull request removes pointers to slices.
> style: remove pointer to slices

- README.md
Quick change to add a banner to the README.md with the current branding banner.
> feat(docs): add banner to README.md

- codehost/github/repositories.go
This pull request introduces a new API to get the default repository branch of a repository. 
Missing tests :-(
> feat: add GetDefaultRepositoryBranch

- codehost/github/pagination.go
This pull request proposes a fix for the related issue.
The paginated request wasn't working correctly on getting the next page results because we were incrementing the page before we checked if the current page that we finished processing is the last page already. If it was the last page we finished the request; if not, we continued to the next page (by incremeting the current page number).
Closes #279 
It was done 2 tests.
1. Ran `task check -f` cmd.
2. Went to a PR with more than 100 events (the 47) on the testing repo and ran the `reviewpad-cli` command on the branch of the PR: `./reviewpad-cli run -p [PULL_REQUEST] -t [GITHUB_TOKEN] -e [EVENT_PAYLOAD] -f [REVIEWPAD_FILE]` where the reviewpad file used the `$lastEventAt` built-in.
> fix: paginated request on next page processing

- engine/exec.go
- engine/lang.go
- engine/loader.go
- engine/loader_test.go
- engine/testdata/loader/transform/reviewpad_after_on_transform.yml
- engine/testdata/loader/transform/reviewpad_before_on_transform.yml
This pull request introduces a new field `on` to a workflow.
This field is a list of strings that can be `pull_request` or `issue`.
Closes #284.
> feat: add on property to workflows

- engine/loader.go
- engine/loader_test.go
- engine/testdata/loader/process/reviewpad_with_inline_rules_after_processing.yml
- engine/testdata/loader/process/reviewpad_with_inline_rules_with_extra_actions.yml
- engine/testdata/loader/process/reviewpad_with_inline_rules_with_extra_actions_after_processing.yml
- engine/testdata/loader/process/reviewpad_with_multiple_inline_rules.yml
- engine/testdata/loader/process/reviewpad_with_multiple_inline_rules_after_processing.yml
This PR introduces support for inline rules with extra actions like below
```
workflows:
- name: size
if:
- rule: "$size < 3"               # inline rule
extra-actions:
- $addLabel("small")
- rule: "$size >= 3 && $size < 5" # inline rule
extra-actions:
- $addLabel("medium")
- rule: "$size > 5"               # inline rule
extra-actions:
- $addLabel("large")
```
How this is implemented is during the loading stage we check if the rule exists in the Reviewpad file and if not we add it to the list of registered rules and refer the newly registered rule in the workflow
Closes #267
Unit Tests and Manual tests
> feat: inline rules with extra actions

- engine/loader.go
- engine/loader_test.go
- engine/testdata/loader/transform/reviewpad_after_kind_transform.yml
- engine/testdata/loader/transform/reviewpad_before_kind_transform.yml
This pull request makes the kind property of a rule optional.
Closes #290.
Unit tests.
> feat: rule kind property is optional

- README.md
"License" has been linked to the License file present in the repository.
> Link License File in ReadMe

- codehost/github/projects_test.go
- lang/aladino/mocks.go
- plugins/aladino/actions/addToProject.go
- plugins/aladino/actions/addToProject_test.go
This pull request adds support for $addToProject() built-in for issues.
Closes #307
> feat: add to project support for issues

- lang/aladino/lex.go
- lang/aladino/parse_test.go
- lang/aladino/parser.go
- lang/aladino/parser.y
Add Lambda functions support
Closes [issue #236](https://github.com/reviewpad/reviewpad/issues/236)
run tests
> feat: lambda function

- lang/aladino/lex.go
- lang/aladino/parse_test.go
- lang/aladino/parser.go
- lang/aladino/parser.y
- lang/aladino/type.go
Add Typed expressions support
Closes [issue #237](https://github.com/reviewpad/reviewpad/issues/237)
run tests
> feat: typed expression

- handler/processors.go
This pull request introduces a fix to the case where a comment is made to a pull request.
> fix: process issue comment separates between issue and pull request

- codehost/github/target/issue_target.go
- codehost/github/target/pull_request_target.go
- codehost/target.go
- engine/transform.go
- plugins/aladino/actions/close.go
- plugins/aladino/actions/close_test.go
This pull request introduces an improvement `$close()` by adding the possibility of closing an issue/pull request with a comment.
Closes #296
Ran `task check -f` cmd and used the `reviewpad-cli run` cmd against a testing repo with `reviewpad.yml` where a triggered rule had the `$close()` action.
> feat: close issue/pull request with comment

- README.md
This pull request adds to the README.md a set of commands that can be run if the user whishes to display the code coverage percentage for all files within the project and/or the total code coverage percentage.
Closes #345 
> chore: update readme with code coverage percentage display cmd

- lang/aladino/parse_test.go
- lang/aladino/parser.go
- lang/aladino/parser.y
This pull request resolves the parse conflicts and adds more unit tests for the parser.
Closes #321
Bug fix (non-breaking change which fixes an issue) 
I have added more tests for the parser capabilities and verified that the parsing conflicts were solved.
> fix: resolve parse conflicts

- codehost/github/pull_requests_test.go
- lang/aladino/parse_test.go
- lang/aladino/parser.go
- lang/aladino/parser.y
This pull request restricts the use of typed expressions to parameters of lambda functions.
Through unit tests.
> feat: restrict typed expressions to lambda parameters

- plugins/aladino/builtins.go
- plugins/aladino/functions/all.go
- plugins/aladino/functions/all_test.go
- plugins/aladino/functions/any.go
- plugins/aladino/functions/any_test.go
This PR introduces the `$all` and `$any` built-in function, which allows checking all values of a list match a certain condition.
```
workflows:
- name: check-assignees
always-run: true
if:
- rule: '$isElementOf("large", $labels()) && $any($assignees(), ($a: String => $isElementOf($a, $group("juniors"))))'
extra-actions:
- '$info("juniors should not be assigned to large pull requests")'
- rule: '$all($assignees(), ($a: String => !$isElementOf($a, $group("security_team"))))'
extra-actions:
- '$info("at least one assignee should be part of the security team")'
```
Closes #348 
Unit & Manual Tests
> feat: any and all built-in functions

- codehost/github/target/pull_request_target.go
- codehost/target.go
- plugins/aladino/actions/assignReviewer.go
- plugins/aladino/actions/assignReviewer_test.go
This pull request introduces the fix to #325
Closes #325
Added new unit tests and ran `task check -f`
> fix: do not request review from a reviewer that has last review approved

- codehost/github/pull_requests_test.go
This pull requests adds unit tests for the the function `GetPullRequestLastPushDate` living at `codehost/github/pull_requests.go`.
Closes #332 
Ran `task check -f` cmd to see if tests were all passing.
> test: add unit tests for GetPullRequestLastPushDate

- plugins/aladino/functions/reviewers.go
- plugins/aladino/functions/reviewers_test.go
The `$reviewers` built-in returns the list of requested reviewers which isn't the expected behavior.
It is expected that this built-in returns the pull request reviewers, i.e, the users that have reviewed the pull request.
This pull request adopts the previous mentioned behavior.
Closes #360 
Ran `task check -f` cmd in order to test the associated tests.
Performed tests against a repository using a `reviewpad.yml` and the `reviewpad-cli` cmd.
> fix: $reviewers return list of requested reviewers

- plugins/aladino/builtins.go
- plugins/aladino/functions/requestedReviewers.go
- plugins/aladino/functions/requestedReviewers_test.go
This pull request introduces a new built-in `$requestedReviewers` that returns the list of the pull request requested reviewers.
This behavior was already implemented by the built-in `$reviewers` however since this behavior was kinda misleading for this built-in (it should return the list of the pull request reviewers and not only the requested ones - fixed in #363), it will be implemented in a new built-in. 
Closes #361 
> feat: $requestedReviewers built-in

- plugins/aladino/functions/isWaitingForReview_test.go
This pull request fixes the `$isWaitingForReview` unit tests that had stopped working due to the change on pull request https://github.com/reviewpad/reviewpad/pull/221 (mainly due to the use of github graphql api).
Closes #331 
Ran `task check -f` cmd in order to check if the developed tests were passing correctly.
Besides it was also checked the code coverage for `$isWaitingForReview` in order to verify if all code was being covered with the new developed unit tests.
> test: fix isWaitingForReview unit tests

- README.md
This pull request introduces changes to the README.md to update the example.
Closes #329 
> docs: update reviewpad example in README.md

- engine/exec.go
This pull request adds to the Mixpanel collector the total count of pipelines.
Manual test with Mixpanel.
> feat: add pipeline count to collector

- codehost/github/target/issue_target.go
- codehost/github/target/pull_request_target.go
- codehost/target.go
- plugins/aladino/actions/removeLabel.go
- plugins/aladino/functions/labels.go
Closes # ([issue](https://github.com/reviewpad/reviewpad/issues/338))
`task test`
`task check -f`
> remove error return from GetLabels()

- codehost/github/repo_test.go
- lang/aladino/mocks.go
- plugins/aladino/actions/rebase_test.go
This pull request adds the unit test for the rebase related functions, which are:
- Rebase (plugins/aladino/actions/rebase.go)
- RebaseOnto (codehost/github/repo.go)
- Push (codehost/github/repo.go)
These functions do not have full coverage because some cases involved permissions, were internal operations performed in git2lib, etc.
Closes #309 
Ran `task test -f` command to check if all developed tests were passing.
> test: add rebase unit tests

- plugins/aladino/actions/assignReviewer_test.go
Issue was fixed in latest master, i only add test for this case to the future
Closes [issue #394](https://github.com/reviewpad/reviewpad/issues/394)
> fix: assignReviewer when 2 reviewers already approve

- lang/aladino/lex.go
- lang/aladino/parse_test.go
- lang/aladino/parser.go
- lang/aladino/parser.y
Defines tokens for aladino types and incorporate them in the parser.
Closes #320 
> fix: parse aladino types

- codehost/github/pull_requests.go
- lang/aladino/mocks.go
- plugins/aladino/actions/deleteHeadBranch.go
- plugins/aladino/actions/deleteHeadBranch_test.go
- plugins/aladino/builtins.go
This PR adds a new builtin action `$deleteHeadBranch()`
Closes #385 
Manual and unit tests.
> feat: delete head branch built in action

- plugins/aladino/builtins.go
- plugins/aladino/functions/hasRequiredApprovals.go
- plugins/aladino/functions/hasRequiredApprovals_test.go
This pull request adds the new built-in `hasRequiredApprovals` that checks if a pull request has the x approvals from a given list of users.
Closes #406 
Ran `task build -f` and `task test -f` cmd.
> feat: hasRequiredApprovals built-in

- README.md
This pull request updates the README.md to reflect the change of usage of Reviewpad.
> docs: update README.md to reflect use of service

- codehost/github/target/issue_target.go
- codehost/github/target/pull_request_target.go
- codehost/target.go
- engine/transform.go
- engine/transform_internal_test.go
- lang/aladino/mocks.go
- plugins/aladino/actions/close.go
- plugins/aladino/actions/close_test.go
This PR introduces an option second parameter to the `$close` built-in action, which allows us to specify the reason an issue was closed.
- add second parameter to `$close` built-in action
Closes #299 
Manual & Unit Tests.
> feat: close with state reason

- go.mod
- go.sum
- rp/aws.go
- rp/convert_types.go
- rp/env.go
This pull request introduces the rp (reviewpad) package.
This package contains common functions to be used accross reviewapd projects.
Run `task check -f`
> feat: add rp package

- lang/aladino/lex.go
- lang/aladino/parse_test.go
- lang/aladino/parser.go
- lang/aladino/parser.y
This PR introduces support for nested array types and function types in aladino.
Closes #410 
Breaking change (fix or feature that would cause existing functionality to not work as expected)
Manual and unit tests.
> feat: nested array and function types

- utils/time.go
- utils/time_test.go
Decreases metric report time verbosity by taking only the first part of the time diff
Closes #442 
Unit tests
> feat: improve metric report

- engine/exec.go
Process where expression in groups using transformers
Closes #434 
Manual tests
> fix: process where expression in groups using transformers

- cli/cmd/run.go
- engine/env.go
- engine/env_test.go
- engine/exec.go
- engine/exec_test.go
- engine/labels_internal_test.go
- engine/mocks.go
- handler/processors.go
- handler/processors_test.go
- lang/aladino/mocks.go
- runner.go
- utils/pr.go
- utils/pr_test.go
This PR introduces the `EventData` struct in order to avoid ballooning the `TargetEntity` and separate event data from target information 
> feat: event data

- plugins/aladino/functions/checkRunConclusion.go
- plugins/aladino/functions/checkRunConclusion_test.go
This pull request add a fix to the builtin checkRunConclusion when the check has no conclusion.
Having no conclusion can happen when the check is, for instance, in progress.
Also, the it can happen that there are several checks for the same ref. When this is the case we need to extract the lastest check conclusion.
> fix: check run conclusion when check is not completed

- codehost/github/pull_requests.go
- codehost/github/target/pull_request_target.go
- plugins/aladino/builtins.go
- plugins/aladino/functions/hasBinaryFile.go
- plugins/aladino/functions/hasBinaryFile_test.go
This PR adds a new `hasBinaryFile` built-in function that returns a boolean value indicating whether a PR has binary file changes.
Closes #477 
Unit & Manual Tests
> feat: add hasBinaryFile built-in function

- Taskfile.yml
Adds `shadow` to task file
Closes #400 
Manually
> feat: add shadow to taskfile

- codehost/github/issues.go
- codehost/github/issues_test.go
- codehost/github/pull_requests.go
- codehost/github/target/common_target.go
- codehost/github/target/issue_target.go
- codehost/github/target/pull_request_target.go
This pull request extends the isLinkedToProject to pull requests.
Closes #492
None.
> feat: extend isLinkedToProject for pull requests

- codehost/github/target/pull_request_target.go
- plugins/aladino/functions/isLinkedToProject_test.go
This pull request introduces a fix to a bug in the underlying call to isLinkedToProject in the codehost package.
> fix: isLinkedToProject API

- cli/cmd/run.go
- runner.go
This pull request introduces the executed program as an output of reviewpad execution.
This feature will allow to interpret and provide the executed program as feedback, e.g. reviewpad playground.
Run `task check -f`
> feat: output executed program

- plugins/aladino/builtins.go
- plugins/aladino/functions/isMerged.go
- plugins/aladino/functions/isMerged_test.go
This PR adds a new built-in function `$isMerged` that returns a boolean value indicating whether a pull request is merged or not.
Closes #505 
Unit Tests
> feat: is merged

- plugins/aladino/builtins.go
- plugins/aladino/functions/isBinary.go
- plugins/aladino/functions/isBinary_test.go
Adds a new `$isBinary()` built-in function that returns a boolean value indicating if a given filename is a binary file or not.
- `$isBinary("README.md")`
- `$isBinary("images/logo.png")`
Closes #527 
Unit & manual tests.
> feat: is binary built-in function

- codehost/github/pull_requests.go
- codehost/github/target/pull_request_target.go
- plugins/aladino/builtins.go
- plugins/aladino/functions/approvalsCount.go
- plugins/aladino/functions/approvalsCount_test.go
Adds a new `approvalsCount` built-in that returns the number of approvals for a pull request.
Closes #528 
Unit tests and manual tests.
> feat: approvals count built-in

- lang/aladino/eval_test.go
This pull request introduces an unit test to verify that eval is working correctly on nested function calls.
Unit tests.
> test: add unit test on eval for nested calls

- engine/labels.go
This pull request introduces a hotfix to fix the label update.
Closes #546 
Hotfix.
> fix: trim prefix hash from label color

- handler/processors.go
- handler/processors_test.go
process `installation` and `installation_repositories` event.
Unit tests
> feat: process installation events

- cli/cmd/run.go
- collector/collector.go
- engine/mocks.go
- lang/aladino/mocks.go
This pull request introduces the parameter options to collector and the new method collect error.
This is to allow the collect to be created with the minium values.
Closes https://github.com/reviewpad/reviewpad/issues/554
Run `task check -f`
> feat: update collector with options

- plugins/aladino/builtins.go
- plugins/aladino/functions/filesPath.go
- plugins/aladino/functions/filesPath_test.go
adds a new `$filesPath` built-in function that returns a list of file paths of the changed files in the patch.
Closes #538 
Unit and Manual tests.
> feat: filesPath built-in function

- engine/transform.go
- engine/transform_internal_test.go
- plugins/aladino/builtins.go
- plugins/aladino/functions/join.go
- plugins/aladino/functions/join_test.go
The pull request introduces the `$join()` built-in function that returns a string value concatenating array elements with separator.
`sprintf` function replaces existing specifiers with the values from `arguments_list `. For this reason passing `$group()`, `$team()`, `$assignees()` or any array of arbitrary size as `arguments_list` could be correct.
Proposed change makes it possible to join arrays into string to replace only one format specifier.
- `$sprintf("These changes require approval by team 'a': %s", [$join($group("a"))])`
Unit tests.
> feat: join built-in function

- plugins/aladino/builtins.go
- plugins/aladino/functions/toNumber.go
- plugins/aladino/functions/toNumber_test.go
Adds a new built-in function `$toNumber`.
- `$toNumber("5")`
- `$toNumber($selectFromContext("$.commits"))`
Closes #584 
Unit tests
> feat: toNumber built-in function

- plugins/aladino/builtins.go
- plugins/aladino/functions/toStringArray.go
- plugins/aladino/functions/toStringArray_test.go
Adds a new built-in function `toStringArray` that converts a given json string to an array of strings or returns an error if string cannot be converted.
Unit and manual tests
> feat: toStringArray built-in function

- collector/collector.go
This pull request introduces mixpanel optional parameters as generic.
Manual tests.
> feat: generic mixpanel optional parameters

- plugins/aladino/actions/review_test.go
This pull request adds the unit tests for the `$review` built-in.
Closes #574 
> test: add unit tests for the review built-in

- handler/processors.go
- handler/processors_test.go
Process `check_run` events.
Unit tests
> feat: process check run event

- codehost/github/client.go
- handler/processors.go
This pull request removes the logger from NewGithubAppClient since it is not necessary.
> Remove logger from github app client

- codehost/github/client_test.go
- codehost/github/target/issue_target.go
- codehost/github/target/pull_request_target.go
- lang/aladino/mocks.go
- plugins/aladino/actions/close_test.go
- plugins/aladino/functions/context_test.go
This pull request introduces the fixes for the failure of the `$close` built-in by replacing the REST API requests with GraphQL requests.
Closes #602 
Manual tests and ran `task check` cmd.
> fix: close built-in failing

- handler/processors.go
- handler/processors_test.go
Process `check_suite` events.
Closes #629 
Unit and Manual tests.
> feat: process check suite events

- README.md
This pull request updates the README with the correct JSON schema configuration being that this schema will only be applied to `reviewpad.yml` files in the root of the repository.
Closes #559 
Manual tests on the IDE.
> chore: update readme with json schema configuration

- lang/aladino/eval.go
Previously we were only collecting action built-in executions to mixpanel, this PR supports collection for other types of built-ins.
Closes #649 
By manually running reviewpad and checking if the proper events are present in mixpanel.
> feat: collect all built-in rans to mixpanel

- handler/processors.go
- handler/processors_test.go
Adds `account type` and `repository visibility` to target entity so that we can use it when collecting events to mixpanel.
Closes #651 
Unit tests
> feat: add account type and visibility to target entity

- README.md
This pull request updates the README.md file with the JSON schema config for `reviewpad.(yml|yaml)` files except for the files that live in the `.github/workflows` directory.
Closes #559 
This piece of configuration added to the README.md was added to the VSCode workspace settings as described and it was checked if the schema would load for the following files:
1. `reviewpad.yml` file in the root directory
2. `reviewpad.yaml` file in the root directory
3. `reviewpad.yml` file in a non-root directory (not being the `.github/workflows` directory)
4. `reviewpad.yaml` file in a non-root directory (not being the `.github/workflows` directory)
And it was checked if the schema wasn't loaded for the `.github/workflows/reviewpad.yml` and …
> feat: update readme with json schema config

- codehost/github/target/pull_request_target.go
- engine/env.go
- integration_test/integration_test.go
- lang/aladino/env.go
- lang/aladino/interpreter.go
- plugins/aladino/actions/disableMerge.go
- plugins/aladino/builtins.go
- runner.go
This pull request introduces the new built-in `disableMerge`.
> feat: buit-in disable merge

- codehost/github/blame.go
- codehost/github/blame_test.go
Adds `SliceBlame` method to github client
Closes #680 
Unit tests
> feat: slice blame

- codehost/github/pull_requests.go
- plugins/aladino/actions/deleteHeadBranch.go
- plugins/aladino/actions/deleteHeadBranch_test.go
Fixes an error with the `$deleteHeadBranch` built-in when the branch to be deleted doesn't exist.
Closes #676 
Manual and unit tests.
> fix: delete head branch when branch doesn't exist

- codehost/github/pull_requests.go
- plugins/aladino/builtins.go
- plugins/aladino/functions/isUpdatedWithBaseBranch.go
- plugins/aladino/functions/isUpdatedWithBaseBranch_test.go
Adds a new built-in `$isUpdatedWithBaseBranch`
Closes #704 
Unit and Manual tests
> feat: is updated with base branch

- plugins/aladino/actions/assignCodeAuthorReviewers.go
- plugins/aladino/actions/assignCodeAuthorReviewers_test.go
Improves the random reviewer selection for the `$assignCodeAuthorReviewers` built-in function.
Closes #709 
Unit and manual tests
> feat: improve random reviewer selection

- plugins/aladino/actions/review.go
- plugins/aladino/actions/review_test.go
- runner.go
- utils/pr.go
- utils/pr_test.go
This pull request introduces a series of fixes for the release.
_none_
> feat: prepare release

- codehost/github/repo.go
The `$rebase` built-in was failing on private repositories because a credential hook wasn't set when cloning, this PR set's the hook.
Closes #730 
**Bug fix** (non-breaking change which fixes an issue)
Manual tests by running the built-in on private repo
> fix: rebase built-in on private repositories

- engine/exec.go
This pull request introduces the fix to only run pipelines on pull requests.
Closes #734
**Bug fix** (non-breaking change which fixes an issue)
Manual tests in the dev app with the example provided in the related issue.
**Ask**: this pull request requires a code review before the merge
> fix: pipelines only run on pull requests

- engine/transform.go
- engine/transform_internal_test.go
- plugins/aladino/builtins.go
- plugins/aladino/functions/hasAnyCheckRunCompleted.go
- plugins/aladino/functions/hasAnyCheckRunCompleted_test.go
Adds a new built-in action `$hasAnyCheckRunComplete` that allows checking if any check run has completed with a desired list of conclusions.
Closes #732 
Unit and Manual tests
> feat: has any check run completed

- engine/exec.go
- engine/inline_rules_normalizer.go
- engine/lang.go
- engine/lang_internal_test.go
- engine/loader.go
- engine/loader_internal_test.go
- engine/loader_test.go
- engine/normalize.go
- engine/normalize_test.go
- runner.go
Removes the API version property since it's no longer used.
Closes #740 
**Improvements** (non-breaking change without functionality)
Unit tests
> chore: remove api version

- lang/aladino/expr.go
Minor linting error.
**Improvements** (non-breaking change without functionality)
CI
**Ship**: this pull request can be automatically merged and does not require code review
> fix: minor lint error

- engine/commands/commands.go
- engine/commands/robin.go
- engine/commands/robin_test.go
- go.mod
- go.sum
- plugins/aladino/actions/robin.go
- plugins/aladino/builtins.go
This pull request integrates with robin in alpha version 1.
> feat: robin integration

- engine/commands/robinPrompt.go
- engine/commands/robinPrompt_test.go
- engine/commands/robinSummarize.go
- engine/commands/robinSummarizeExtended.go
- engine/commands/robinSummarizeExtended_test.go
- engine/commands/robinSummarize_test.go
- engine/commands/robin_test.go
- go.mod
- go.sum
- plugins/aladino/actions/robinPrompt.go
- plugins/aladino/actions/robinSummarize.go
This pull request updates robin interactions to include a model parameter.
Ongoing
**Ship**: this pull request can be automatically merged and does not require code review
> feat: add model parameter to robin API calls

- integration_test/integration_test.go
Fixes the codehost client intialization in the integration tests.
Closes #801 
**Bug fix** (non-breaking change which fixes an issue)
Manual tests
> test: fix codehost client creation in integration tests

- codehost/github/repositories.go
- engine/loader.go
- plugins/aladino/semantic/symbols.go
- utils/file.go
Reverts reviewpad/reviewpad#920
**Ship**: this pull request can be automatically merged and does not require code review
> feat(revert): download gh repo contents through commit SHA
